### ISSUE TITLE
[BUG] Demo site has cors error

### ISSUE THREAD

**Issue by Mistat** [fabrix-framework/editor#8]
**Describe the bug**

The demo site `https://fabrix-framework.github.io/editor/` does not work. Because of CORS error.

**To Reproduce**
1. Go to `https://fabrix-framework.github.io/editor/`
2. Put any queries
3. See error

**Expected behavior**

Background API `https://starwars-9teh3dbd8w.erp.dev/query`'s cors setting is wrong.

**Screenshots**
<img width="1308" alt="Screenshot 2024-09-28 at 12 16 28" src="https://github.com/user-attachments/assets/c8973e78-ca35-429b-8598-445ab21a9579">

**Desktop (please complete the following information):**

**Additional context**

**Comment by jackchuka** [comment]
Thanks for reporting. It was a temporary issue, but it should work as expected.
